version: '2'
services:
    api:
        build: .
        command: node_modules/.bin/nodemon
        depends_on:
            - service-db
            - service-redis
        ports:
            - 3000:3000
        volumes:
            - .:/home/app/src
    service-db:
        image: mongo
        ports:
            - 27017:27017
    service-redis:
        image: redis
        ports:
            - 6379:6379